# This file was generated by Flutter, do not edit.
# This file is used by the `flutter` tool to generate the necessary integration
# code for your app.

require 'xcodeproj'

def flutter_root
  generated_xcode_project_path = File.expand_path(File.join('..', '..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_project_path)
    raise "#{generated_xcode_project_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_project_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_project_path}. Try running 'flutter pub get' in the project root."
end

def flutter_application_path
  File.expand_path(File.join('..', '..'), __FILE__)
end

def flutter_pods_ios_path
  File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
end

def flutter_install_all_ios_pods(ios_application_path = nil)
  flutter_install_all_ios_pods_file(ios_application_path)
end

def flutter_install_all_ios_pods_file(ios_application_path)
  ios_application_path ||= File.dirname(File.realpath(__FILE__))
  pod 'Flutter', :path => File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
end

def flutter_post_install(installer)
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

def flutter_additional_ios_build_settings(target)
  target.build_configurations.each do |config|
    config.build_settings['ENABLE_BITCODE'] = 'NO'
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
  end
end
