name: Build iOS unsigned IPA

on:
  workflow_dispatch:  # Elle çalıştıracaksın

jobs:
  build:
    runs-on: macos-15  # macOS 15 (Sonoma) kullan

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.27.0'  # Daha yeni Flutter versiyonu

      - name: Flutter version
        run: flutter --version

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Setup iOS build environment
        run: |
          sudo xcode-select --switch /Applications/Xcode_16.0.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Clean Flutter
        run: |
          flutter clean
          flutter pub get

      # Flutter iOS dosyalarını oluştur
      - name: Generate Flutter iOS files
        run: |
          flutter precache --ios
          flutter build ios --debug --no-codesign --simulator
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer

      # Şimdi pod install yap (podhelper.rb artık mevcut)
      - name: Install iOS dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      # SON BUILD: Release için
      - name: Build iOS Release (no codesign)
        run: |
          flutter build ios --release --no-codesign
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer

      # IPA paketleme
      - name: Package unsigned IPA
        run: |
          rm -rf Payload
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
          zip -r NiksarMobil-unsigned.ipa Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NiksarMobil-unsigned
          path: NiksarMobil-unsigned.ipa
